### ISSUE TITLE
Fix light curve viewer bugs (consolidated list)

### ISSUE THREAD

**Issue by saschaishikawa** [zooniverse/Planet-Hunters-2#190]
Consolidated issues pertaining to light curve viewer
- [ ] mark close to y-axis right handside can't adjust handles or drag to make bigger (resolves #170)
- [ ] default minimum mark size is larger for box drawn right near the y-axis on the right (resolves #167)
- [x] zooming to 2nd level and drawing mark shifts all existing marks after zooming out (resolves #160)
- [ ] allow more overlap between marks (resolves #158)
- [x] bring back light curve measuring tool (a.k.a. the red line) (resolves #157)
- [x] can't place mark at left edge (resolves #95)
- [x] make axes brigthter
